name: "Pre-Release"

on:
  push:
    branches:
      - "master"

jobs:
  run-tests:
    name: "Run Test Cases"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: gradle
      - name: Run Tests
        run: ./gradlew test --stacktrace
      
  publish-pre-release:
    name: "Publish Pre-Release"
    runs-on: "ubuntu-latest"
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Tests
        run: ./gradlew assembleDebug
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ls -la ./app/
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "WoW Auction House Browser"
          files: |
            ./app/build/ouputs/apk/debug/app-debug.apk
