name: "Pre-Release"

on:
  push:
    branches:
      - "master"

jobs:
  run-tests:
    name: "Run Test Cases"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: gradle
      - name: Run Tests
        run: bash ./gradlew test --stacktrace
      
  publish-pre-release:
    name: "Publish Pre-Release"
    runs-on: "ubuntu-latest"
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pre-Release
        id: create_pre_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Pre-Release ${{ github.ref }}
          body: |
            ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: true
